README.md
Add an explanatory note and link to the other repo which is current still powering the 'live' site
=> live site currently powered by the other repo

locales/de/LC_MESSAGES/djangojs.po, locales/en/LC_MESSAGES/djangojs.po, locales/es/LC_MESSAGES/djangojs.po, locales/fr/LC_MESSAGES/djangojs.po, locales/id/LC_MESSAGES/djangojs.po, locales/ja/LC_MESSAGES/djangojs.po, ui/static/ui/js/clone.js, ui/static/ui/js/create.js
=> Flip East and West

ui/app/hdx/components/HDXExportRegionForm.jsx
removes admin boundaries, adds some tags, standardizes order of
addr:full
=> changes to the feature selector

ui/app/actions/aoi/mapToolActions.js
=> support FeatureCollection and (closed) LineString

ui/app/app.js, ui/package.json, ui/public/index.html
We have updated our website tracking, and have added an opt-out form for gdpr compliance.
=> Matomo tracking

ui/app/utils/TreeTagSettings.js, ui/app/utils/tagtree.csv
fixes #346 
Additional values taken from https://wiki.openstreetmap.org/wiki/Key:place#Values
=> adding place values to the localities > place tree node

core/settings/project.py, hdx_exports/hdx_export_set.py, jobs/models.py, tasks/task_runners.py
- hotosm/galaxy-api/issues/236 
- https://github.com/hotosm/galaxy-api/issues/235
- https://github.com/hotosm/galaxy-api/issues/235
=> HDX Exports Enabled with Galaxy 

requirements.txt, tasks/task_runners.py
=> Hotfix : Worker stuck issue due to timeout 

ui/app/components/ExportDetails.js, ui/app/components/NavBar.js
- Also contirbutes to #422
- Resolves geocode fix on production
=> Missing files from Production

api/views.py
=> Fix for idx not defined

.github/workflows/config.yml, api/urls.py, api/views.py, core/settings/project.py, core/urls.py, core/wsgi.py, requirements.txt, tasks/models.py, tasks/task_runners.py, ui/app/components/NavBar.js, ui/views.py
- May contribute to #380
- Resolve #435 
- Resolve #436 
- Resolve #437 through 97f9e18858d31491f969ad9f29bd98f343d9ebb0
This PR introduces dramatiq dashboard and formats export tasks on django admin . It also adds timeout error handling as well as individual task error handling and updating respective row on database about the task alongside run
=> Feature : Better Visualization  Metrics 

api/views.py
changed response to json and added overpass / galaxy timestamp
=> Enhance : Status Endpointv

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md
adding templates that can be helpful for users after launch
=> Adding BUG and FEATURE templates

api/views.py
=> Quick Fix : Bug : Last updated 

api/views.py, hdx_exports/hdx_export_set.py
- Added support to display Country boundary from Backend ```country country_name_for_search```
- Can search for osm elements to download using ``` osm element_osm_id```
- Migrated TM search to , search should start with ```tm tm_project_id```
=> Enhances Search Functionality

tasks/task_runners.py
=> Limit of scheduled jobs : 12 hour 

ui/app/components/help/ExportFormats.js
Towards the issue: #483
Added documentation for file formats: 
- .geojson
- .fgb
- .csv
- .sql
=> Update Export Tool Documentation-File Formats

jobs/models.py
- Added index on job created at field , It will improve the speed of the query
=> Enhance : Stats for Job

ui/app/components/aoi/ExportAOI.js
See: https://github.com/openstreetmap/operations/issues/737
=> Update ExportAOI.js use correct tile.osm.org URL

ui/app/components/MapListView.js
See https://github.com/openstreetmap/operations/issues/737
=> Update MapListView.js use correct tile.osm.org URL

api/views.py, core/settings/project.py, requirements.txt, tasks/models.py, tasks/task_runners.py, ui/app/actions/exports.js
- Implements authentication for Raw Data API
=> Feature Raw Data API Authentication
